/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as Phase6RouteImport } from './routes/phase-6'
import { Route as Phase5RouteImport } from './routes/phase-5'
import { Route as Phase4RouteImport } from './routes/phase-4'
import { Route as Phase3RouteImport } from './routes/phase-3'
import { Route as Phase2RouteImport } from './routes/phase-2'
import { Route as Phase1RouteImport } from './routes/phase-1'
import { Route as IndexRouteImport } from './routes/index'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase6Route = Phase6RouteImport.update({
  id: '/phase-6',
  path: '/phase-6',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase5Route = Phase5RouteImport.update({
  id: '/phase-5',
  path: '/phase-5',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase4Route = Phase4RouteImport.update({
  id: '/phase-4',
  path: '/phase-4',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase3Route = Phase3RouteImport.update({
  id: '/phase-3',
  path: '/phase-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase2Route = Phase2RouteImport.update({
  id: '/phase-2',
  path: '/phase-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase1Route = Phase1RouteImport.update({
  id: '/phase-1',
  path: '/phase-1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/phase-1': typeof Phase1Route
  '/phase-2': typeof Phase2Route
  '/phase-3': typeof Phase3Route
  '/phase-4': typeof Phase4Route
  '/phase-5': typeof Phase5Route
  '/phase-6': typeof Phase6Route
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/phase-1': typeof Phase1Route
  '/phase-2': typeof Phase2Route
  '/phase-3': typeof Phase3Route
  '/phase-4': typeof Phase4Route
  '/phase-5': typeof Phase5Route
  '/phase-6': typeof Phase6Route
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/phase-1': typeof Phase1Route
  '/phase-2': typeof Phase2Route
  '/phase-3': typeof Phase3Route
  '/phase-4': typeof Phase4Route
  '/phase-5': typeof Phase5Route
  '/phase-6': typeof Phase6Route
  '/roadmap': typeof RoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/phase-1'
    | '/phase-2'
    | '/phase-3'
    | '/phase-4'
    | '/phase-5'
    | '/phase-6'
    | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/phase-1'
    | '/phase-2'
    | '/phase-3'
    | '/phase-4'
    | '/phase-5'
    | '/phase-6'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/phase-1'
    | '/phase-2'
    | '/phase-3'
    | '/phase-4'
    | '/phase-5'
    | '/phase-6'
    | '/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Phase1Route: typeof Phase1Route
  Phase2Route: typeof Phase2Route
  Phase3Route: typeof Phase3Route
  Phase4Route: typeof Phase4Route
  Phase5Route: typeof Phase5Route
  Phase6Route: typeof Phase6Route
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-6': {
      id: '/phase-6'
      path: '/phase-6'
      fullPath: '/phase-6'
      preLoaderRoute: typeof Phase6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-5': {
      id: '/phase-5'
      path: '/phase-5'
      fullPath: '/phase-5'
      preLoaderRoute: typeof Phase5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-4': {
      id: '/phase-4'
      path: '/phase-4'
      fullPath: '/phase-4'
      preLoaderRoute: typeof Phase4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-3': {
      id: '/phase-3'
      path: '/phase-3'
      fullPath: '/phase-3'
      preLoaderRoute: typeof Phase3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-2': {
      id: '/phase-2'
      path: '/phase-2'
      fullPath: '/phase-2'
      preLoaderRoute: typeof Phase2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-1': {
      id: '/phase-1'
      path: '/phase-1'
      fullPath: '/phase-1'
      preLoaderRoute: typeof Phase1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Phase1Route: Phase1Route,
  Phase2Route: Phase2Route,
  Phase3Route: Phase3Route,
  Phase4Route: Phase4Route,
  Phase5Route: Phase5Route,
  Phase6Route: Phase6Route,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
